services:
  usbtortsp:
    build: .
    container_name: usbtortsp
    network_mode: "host"
    ports:
      - "554:554"
    environment:
      - RTSP_RTSPADDRESS=0.0.0.0:554
      - CAMERA_PATH=/dev/video0
      - RESOLVE=1280x720
      - FPS=25
      - METHODE=tcp
    devices:
      - "/dev/video0:/dev/video0"