FROM ubuntu:22.04


COPY ./start.sh /start.sh
RUN chmod +x /start.sh


RUN apt-get update && \
    apt-get install -y htop nano git curl wget ffmpeg


RUN wget https://github.com/bluenviron/mediamtx/releases/download/v0.16.0/rtsp-simple-server_v0.16.0_linux_amd64.tar.gz && \
    tar -xzvf rtsp-simple-server_v0.16.0_linux_amd64.tar.gz && \
    mv rtsp-simple-server /usr/local/bin && \
    rm rtsp-simple-server_v0.16.0_linux_amd64.tar.gz


EXPOSE 8445
EXPOSE 8888
EXPOSE 8001
EXPOSE 8000
EXPOSE 1935
EXPOSE 554


CMD ["/start.sh"]